/* eslint-disable one-var */
export const COMPONENT_SAVE_PENDING = 'COMPONENT_SAVE_PENDING';
export const COMPONENT_SAVE_FAILURE = 'COMPONENT_SAVE_FAILURE';
export const COMPONENT_SERVER_SAVE_SUCCESS = 'COMPONENT_SERVER_SAVE_SUCCESS';
